Выполнение заданий по лекции "Лямбда-функции"
pavelsmirnov77/sber-practice_core_java pull request #4
Opened 2022-07-09 17:59 UTC by pavelsmirnov77

2022-07-10 06:21 UTC, XLelarX requested changes
Проверку всего кода надо делать через тесты, а не метод main. Не зря же мы их изучали)

2022-07-10 06:21 UTC, XLelarX commented on Stream/src/ru/sber/stream/StreamClass.java
> +        for (int i = 0; i < 3; i++) {
Всю задачу необходимо сделать через один стрим. Никаких list.remove и подсчета среднего числа своими силами тут не нужно

2022-07-10 06:21 UTC, XLelarX commented on Stream/src/ru/sber/stream/StreamClass.java
> +        set.forEach(elem -> System.out.print(elem + " "));
Выводить коллекции можно через обычный sout, а не через цикл

2022-07-10 06:21 UTC, XLelarX commented on Stream/src/ru/sber/stream/StreamClass.java
> +        Map<String, String> map = set.stream().filter(elem -> elem.length() > 10).collect(Collectors.toMap(key -> key + "-key", value -> value));
Функции типа value -> value нужно заменять на **Function.identity()**

2022-07-10 06:21 UTC, XLelarX commented on Stream/src/ru/sber/stream/StreamClass.java
> +        for (String key : listKeys) {
В 3 задании нужно использовать стримы, а не циклы

2022-07-10 06:21 UTC, XLelarX commented on Stream/src/ru/sber/stream/StreamClass.java
> +        Optional.ofNullable(stream);
Метод должен возвращать новый экземпляр, передаваемого в параметрах класса, только если он равен null

2022-07-10 06:21 UTC, XLelarX commented on Stream/src/ru/sber/stream/StreamClass.java
> +    }
Пробел поехал. Используй форматирование идеи

2022-07-11 10:20 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/OneArgFunctionalInterface.java
> +public interface OneArgFunctionalInterface<N> {
Исправлено

2022-07-11 10:20 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/ZeroArgsFunctionalInterface.java
> +    public void zeroArgsMethod();
Исправлено

2022-07-11 10:20 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/Lambda.java
> +        Predicate predicate = new Predicate() {
Исправлено

2022-07-11 10:20 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/Lambda.java
> +        methodConsumer((a) -> {
Исправлено

2022-07-11 10:20 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/Lambda.java
> +            System.out.println("Первый метод вызван через лямбда-функцию");
Исправлено

2022-07-11 10:20 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/Lambda.java
> +        Function<String, String> function = new Function<String, String>() {
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Lambda/src/ru/sber/lambda/Lambda.java
> +        Supplier<Integer> supplier = new Supplier<Integer>() {
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +        List<Integer> newList = Stream.concat(listEvenElements.stream(), listNotEvenElements.stream()).toList();
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +        for (int i = 0; i < 3; i++) {
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +        set.forEach(elem -> System.out.print(elem + " "));
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +        Map<String, String> map = set.stream().filter(elem -> elem.length() > 10).collect(Collectors.toMap(key -> key + "-key", value -> value));
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +        for (String key : listKeys) {
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +        Optional.ofNullable(stream);
Исправлено

2022-07-11 10:21 UTC, pavelsmirnov77 commented on Stream/src/ru/sber/stream/StreamClass.java
> +    }
Исправлено

2022-07-11 18:28 UTC, XLelarX commented on Lambda/src/main/java/lambda/Lambda.java
> +    public static void methodConsumer(Consumer consumer) {
Consumer -> Consumer<String>

2022-07-11 18:38 UTC, XLelarX commented on Stream/src/test/java/stream_api/StreamClassTest.java
> +                .getAsDouble());
Вся задача должна делаться через ОДИН стрим. Без всяких 2 листов и их конкатенации

2022-07-11 18:41 UTC, XLelarX commented on Stream/src/test/java/stream_api/StreamClassTest.java
> +        System.out.println();
Не нужны

2022-07-11 19:48 UTC, pavelsmirnov77 commented on Lambda/src/main/java/lambda/Lambda.java
> +    public static void methodConsumer(Consumer consumer) {
Исправил Consumer на Consumer<String>

2022-07-11 19:49 UTC, pavelsmirnov77 commented on Lambda/src/test/java/lambda/LambdaTest.java
> +                System.out.println("Первый метод вызыван");
Добавил константы

2022-07-11 19:50 UTC, pavelsmirnov77 commented on Stream/src/test/java/stream_api/StreamClassTest.java
> +        list.forEach(elem -> System.out.print(elem + " "));
Поставил везде sout где нужно

2022-07-11 19:50 UTC, pavelsmirnov77 commented on Stream/src/test/java/stream_api/StreamClassTest.java
> +                .getAsDouble());
Исправил

2022-07-11 19:50 UTC, pavelsmirnov77 commented on Stream/src/test/java/stream_api/StreamClassTest.java
> +        System.out.println();
Убрал

2022-07-11 21:22 UTC, XLelarX approved these changes

2022-07-11 21:22 UTC, XLelarX commented on Stream/src/test/java/stream_api/StreamClassTest.java
> +                .map(elem -> (elem%2 == 0) ? elem + 5 : elem - 5)
пробельчик бы тут. Прожми форматирование

2022-07-11 21:23 UTC, merged